language: node_js
sudo: false
node_js:
  - 0.12
  - 4
  - 5

cache:
  directories:
    - node_modules

script:
  - npm build
  - npm test

deploy:
  provider: npm
  email: lamo2k123@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: plasticinejs/plasticine.js